version: '2.1'
services:
    redis:
        image: 'redis:5.0.5'
        ports:
          - "6379:6379"
    webserver:
        image: puckel/docker-airflow:1.10.6
        restart: always
        depends_on:
            - postgres
            - redis
        volumes:
            - ./dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
    flower:
        image: puckel/docker-airflow:1.10.6
        restart: always
        depends_on:
            - redis
        ports:
            - "5555:5555"
        command: flower
    scheduler:
        image: puckel/docker-airflow:1.10.6
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
        command: scheduler
    worker:
        image: puckel/docker-airflow:1.10.6
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
        command: worker
    worker:
        image: puckel/docker-airflow:1.10.6
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
        command: worker
    worker:
        image: puckel/docker-airflow:1.10.6
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
        command: worker
    worker:
        image: puckel/docker-airflow:1.10.6
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
        command: worker